version: "3"
services:
  angular-app:
    build:
      context: ./src-frontend
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - spring-boot-app

  spring-boot-app:
    build:
      context: ./src-api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/automobile
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: automobile
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: